### ISSUE TITLE
The final step of "Setup"

### ISSUE THREAD

**Issue by ashley915** [amzn/amazon-dsstne#150]
On the final step of the setup, I'm having issues with "make". 
I've managed to work through numerous errors while processing make, but it seems this error cannot be solved on my own. 
The error states:
error: 'class Json::ValueIterator' has no member named 'name'

and this happens several times while processing make. 
I've been stuck on setup for three days now, so plz help me out. 
I'm using my own linux laptop, and is currently using ubuntu 14.04 ver. 

I am in desperate need of help. Thank you

**Comment by rgeorgej** [comment]
Are you  using Docker or plain vanilla instance ?

**Comment by ashley915** [comment]
I haven't set up Docker so yes, vanilla instance. Does that mean that I should use Docker?

**Comment by ekandrotA9** [comment]
You need to use 16.04 - it is fixed in that version of the library.  The library changed, but there is no version number in their code, so we can not compile around it.

**Comment by rgeorgej** [comment]
@ashley915  is it possible for you to use Docker with ubuntu 16.04  ??

**Comment by ashley915** [comment]
no, I still won't be using Docker... Will it still cause the same error without it?

**Comment by scottlegrand** [comment]
You need to be in Ubuntu 16.04 either natively or within a docker container
to get around this alas...

**Comment by ashley915** [comment]
Thanks! I successfully ran dsstne with the sample movie lens data with ubuntu 16.04- but I have one more quick question. 

The data converts the csv file into a ml-20_ratings text file through awk file, right?
But after this step it seems that the ratings of each movie the users gave are left out in the input file, which seems a bit off to me, since rating appears to be the most important data with recommendation system.

Is there a reason behind this- or am I interpreting this in a wrong way?
